export enum EventType {
  SET_MAIN_LIST_CONTEXT = 'SET_MAIN_LIST_CONTEXT',
  SET_MAIN_LIST_LOADING = 'SET_MAIN_LIST_LOADING',
  SET_MAIN_LIST_DATA = 'SET_MAIN_LIST_DATA',
  OPEN_ADD_USER_MODAL = 'OPEN_ADD_USER_MODAL',
  UPDATE_ADD_USER_FIELD = 'UPDATE_ADD_USER_FIELD',
  RESET_ADD_USER_MODAL = 'RESET_ADD_USER_MODAL',
  ADD_USER_IN_PROGRESS = 'ADD_USER_IN_PROGRESS',
  OPEN_MANAGE_USER = 'OPEN_MANAGE_USER',
  CLEAR_MANAGE_USER = 'CLEAR_MANAGE_USER',
  POPULATE_USER_POLLS = 'POPULATE_USER_POLLS',
  SET_ACTIVE_USER = 'SET_ACTIVE_USER',
  OPEN_CREATE_POLL_MODAL = 'OPEN_CREATE_POLL_MODAL',
  CREATE_POLL_UPDATE_TITLE = 'CREATE_POLL_UPDATE_TITLE',
  CREATE_POLL_ADD_OPTION = 'CREATE_POLL_ADD_OPTION',
  CREATE_POLL_REMOVE_OPTION = 'CREATE_POLL_REMOVE_OPTION',
  CREATE_POLL_OPTION_VALUE = 'CREATE_POLL_OPTION_VALUE',
  CREATE_POLL_IN_PROGRESS = 'CREATE_POLL_IN_PROGRESS',
  RESET_CREATE_POLL_MODAL = 'RESET_CREATE_POLL_MODAL',
  OPEN_VIEW_POLL = 'OPEN_VIEW_POLL',
  CLEAR_VIEW_POLL = 'CLEAR_VIEW_POLL',
  POLL_VIEW_MODE = 'POLL_VIEW_MODE',
  SET_POLL_RESULTS = 'SET_POLL_RESULTS',
  SET_POLL_RESPONSES = 'SET_POLL_RESPONSES',
  OPEN_VOTE_MODAL = 'OPEN_VOTE_MODAL',
}

export interface IEvent {
  type: EventType;
}
